[package]
name = "tjo-cloud-console"
version = "0.1.0"
edition = "2024"

[dependencies]
# Actix
actix-web = "4"
# Kube
kube = { version = "2.0.1", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.26.0", features = ["latest", "schemars"] }
schemars = { version = "1" }
