s3:
  url: "http://localhost:3903"
  token: "5lVvod7yaZM7MtMRJ32Jd8VssQ01ehj1xVaEnikqhxg="

postgresql:
  localhost:
    host: "localhost"
    user: "postgres"
    password: "postgres"
    sslmode: "disable"
