apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: console
  labels:
    app.kubernetes.io/name: console
    app.kubernetes.io/part-of: console-tjo-cloud
rules:
- apiGroups: [""]
  resources: ["secret"]
  verbs: ["get", "delete"]
- apiGroups: ["postgresql.tjo.cloud"]
  resources: ["Database", "User"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["s3.tjo.cloud"]
  resources: ["Bucket", "Token"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: console
  labels:
    app.kubernetes.io/name: console
    app.kubernetes.io/part-of: console-tjo-cloud
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: console
  labels:
    app.kubernetes.io/name: console
    app.kubernetes.io/part-of: console-tjo-cloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: console
subjects:
- kind: ServiceAccount
  name: console
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: console
  labels:
    app.kubernetes.io/name: console
    app.kubernetes.io/part-of: console-tjo-cloud
data:
  settings.yaml: |
    s3:
      url: "https://api.s3.tjo.cloud"

    postgresql:
      endor-one:
        host: "endor-one.postgresql.tjo.cloud"
        user: "svc-console-tjo-cloud"
        sslmode: "require"
        database: "postgres"
      nevaroo-one:
        host: "nevaroo-one.postgresql.tjo.cloud"
        user: "svc-console-tjo-cloud"
        sslmode: "require"
        database: "postgres"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  labels:
    app.kubernetes.io/name: console
    app.kubernetes.io/part-of: console-tjo-cloud
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: console
      app.kubernetes.io/part-of: console-tjo-cloud
  template:
    metadata:
      labels:
        app.kubernetes.io/name: console
        app.kubernetes.io/part-of: console-tjo-cloud
    spec:
      serviceAccountName: console
      securityContext:
        runAsUser: 1000
      containers:
        - name: console
          image: code.tjo.space/tjo-cloud/console:0.1.0-3c9a6c7-dev
          ports:
            - containerPort: 8080
              name: http
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          resources:
            limits:
              memory: "200Mi"
              cpu: "100m"
          envFrom:
            - secretRef:
                name: console
          volumeMounts:
            - name: settings
              mountPath: "/etc/console"
              readOnly: true
      volumes:
        - name: settings
          configMap:
            name: console
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: console
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: console
      app.kubernetes.io/part-of: console-tjo-cloud
  podMetricsEndpoints:
    - port: http
